apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb-sts
  name: mariadb-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-sts
  serviceName: mariadb-svc
  template:
    metadata:
      labels:
        app: mariadb-sts
    spec:
      containers:
      - image: mariadb:10.7.7
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_ROOT_PASSWORD
              optional: false

